title: Just the Docs Template - Test
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://eyw7-cdc.github.io/just-the-docs-test

aux_links:
  Template Repository: https://github.com/eyw7-cdc/just-the-docs-test/
